apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nrao-provisioner-log-pvc-24
  namespace: osg-nrao
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
