apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: direct-provisioner-log-pvc
  namespace: osg-ligo
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
