#
# These worker nodes will be prempted, use with care
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osg-wn-cpu-opt4
  namespace: osgcpus
  labels: 
    k8s-app: osg-wn-cpu-opt4
spec:
  replicas: 10
  selector:
    matchLabels:
      k8s-app: osg-wn-cpu-opt4
  template:
    metadata: 
      labels:
        k8s-app: osg-wn-cpu-opt4
    spec:
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: NotIn
                values:
                - osg
                - I2
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/noceph
        operator: Exists
      containers:
      - name: wn
        image: sfiligoi/prp-osg-pool:wn-cpu
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        # start shutdown as soon as possible, so the job has time to cleanup
        lifecycle:
          preStop:
            exec:
              command: ["/usr/bin/kill","1"]
        resources:
           limits:
             memory: 13Gi
             cpu: 6
           requests:
             memory: 10Gi
             cpu: 3
             # we will schedule 4 jobs, but expect 75% efficiency
        volumeMounts:
        - name: configpasswd
          mountPath: /var/lock/condor/pool_password
          subPath: pool_password
          readOnly: true
        - name: confighost
          mountPath: /etc/condor/config.d/50_condor_host.config
          subPath: 50_condor_host.config
        - name: configmem
          mountPath: /etc/condor/config.d/02_memory_limits_10g.config
          subPath: 02_memory_limits_10g.config
        - name: configic
          mountPath: /etc/condor/config.d/09_icecube.config
          subPath: 09_icecube.config
        - name: configusers
          mountPath: /usr/local/sbin/add_image_users.sh
          subPath: add_image_users.sh
        - mountPath: /cvmfs/config-osg.opensciencegrid.org
          name:  cvmfs-config-osg
          readOnly: true
        - mountPath: /cvmfs/oasis.opensciencegrid.org
          name:  cvmfs-oasis
          readOnly: true
        - mountPath: /cvmfs/singularity.opensciencegrid.org
          name:  cvmfs-singularity
          readOnly: true
        - mountPath: /cvmfs/ligo-containers.opensciencegrid.org
          name:  cvmfs-ligo-containers
          readOnly: true
        - mountPath: /cvmfs/icecube.opensciencegrid.org
          name:  cvmfs-icecube
          readOnly: true
        - mountPath: /cvmfs/xenon.opensciencegrid.org
          name:  cvmfs-xenon
          readOnly: true
        - mountPath: /cvmfs/nova.opensciencegrid.org
          name:  cvmfs-nova
          readOnly: true
        - mountPath: /cvmfs/fermilab.opensciencegrid.org
          name:  cvmfs-fermilab
          readOnly: true
        - mountPath: /cvmfs/connect.opensciencegrid.org
          name:  cvmfs-connect
          readOnly: true
        - mountPath: /cvmfs/stash.osgstorage.org
          name:  cvmfs-stash
          readOnly: true
      volumes:
      - name: cvmfs-config-osg
        persistentVolumeClaim:
          claimName: cvmfs-config-osg
      - name: cvmfs-oasis
        persistentVolumeClaim:
          claimName: cvmfs-oasis
      - name: cvmfs-singularity
        persistentVolumeClaim:
          claimName: cvmfs-singularity
      - name: cvmfs-ligo-containers
        persistentVolumeClaim:
          claimName: cvmfs-ligo-containers
      - name: cvmfs-icecube
        persistentVolumeClaim:
          claimName: cvmfs-icecube
      - name: cvmfs-xenon
        persistentVolumeClaim:
          claimName: cvmfs-xenon
      - name: cvmfs-nova
        persistentVolumeClaim:
          claimName: cvmfs-nova
      - name: cvmfs-fermilab
        persistentVolumeClaim:
          claimName: cvmfs-fermilab
      - name: cvmfs-connect
        persistentVolumeClaim:
          claimName: cvmfs-connect
      - name: cvmfs-stash
        persistentVolumeClaim:
          claimName: cvmfs-stash
      - name: configpasswd
        secret:
          secretName: osg-pool-sdsc-config
          items:
             - key: pool_password
               path: pool_password
          defaultMode: 256
      - name: confighost
        configMap:
          name: osg-wn-prp-config
          items:
             - key: 50_condor_host.config
               path: 50_condor_host.config
      - name: configmem
        configMap:
          name: osg-wn-prp-cpu-config
          items:
             - key: 02_memory_limits_10g.config
               path: 02_memory_limits_10g.config
      - name: configic
        configMap:
          name: osg-wn-prp-cpu-config
          items:
             - key: 09_icecube.config
               path: 09_icecube.config
      - name: configusers
        configMap:
          name: osg-wn-prp-config
          items:
             - key: add_image_users.sh
               path: add_image_users.sh

