apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osg-provisioner-log-pvc
  # must specify namespace at cmdline
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
